name: Secret test Workflow

on: [workflow_dispatch]

jobs:
  secret-management-check:
    runs-on: ubuntu-latest
    steps:
      - name: echo secrets, printing to the screen
        run: echo ${{ secrets.MY_SENSITIVE_TOKEN }}