name: security gate Workflow

on: [push]

jobs:
  security-gate-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Password File
        run: | 
            if [ -f passwords.txt ]; then
              echo "Password file exists. Proceeding with security checks."
            else
              echo "No password file found. Exiting."
              exit 1
            fi

      - name: Security Gate Verification
        run: echo "Security Gate Check Passed - No Issues Detected"