name: security gate Workflow

on: [push]

jobs:
  security-gate-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Check Password File
        run: |
          [ -f passwords.txt ] && { echo "Error: passwords.txt found"; exit 1; } || exit 0