name: security gate Workflow

on: [push]

jobs:
  security-gate-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Password File
        run: | 
            if [ -f passwords.txt ]; then
              echo "Password file exists. Exiting"
                exit 1
            else
              echo "Password file not found. Continue."
            fi